import { Landlord, Property, Unit, Tenant, Tenancy, RentInvoice, Payment, Receipt, NotificationRecord, MaintenanceTicket, ExpenseRecord } from './types';

export const INITIAL_LANDLORDS: Landlord[] = [
  {
    id: 'lnd_christian_ahugbah',
    name: 'Christian Ahugbah',
    businessName: 'Ahugbah Real Estate & Asset Management',
    email: 'wonderahiabli@gmail.com',
    phone: '+233 24 456 7890',
    ghanaCardNumber: 'GHA-712893450-8',
    bankDetails: {
      bankName: 'Ecobank Ghana Ltd',
      accountNumber: '1441002938102',
      accountName: 'Ahugbah Real Estate & Asset Mgt',
    },
    momoDetails: {
      network: 'MTN MoMo',
      phoneNumber: '0244567890',
      merchantName: 'RentFlow - Ahugbah Estates',
    },
  },
  {
    id: 'lnd_kojo_asante',
    name: 'Kojo Asante',
    businessName: 'Asante Properties Ltd',
    email: 'k.asante@asanteproperties.com.gh',
    phone: '+233 20 812 3456',
    ghanaCardNumber: 'GHA-829103945-2',
    bankDetails: {
      bankName: 'GCB Bank PLC',
      accountNumber: '1092049182390',
      accountName: 'Kojo Asante Properties',
    },
    momoDetails: {
      network: 'Telecel Cash',
      phoneNumber: '0208123456',
      merchantName: 'Asante Holdings',
    },
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_east_legon',
    landlordId: 'lnd_christian_ahugbah',
    name: 'East Legon Luxury Court',
    type: 'Apartment Complex',
    address: '14 Lagos Avenue, East Legon',
    city: 'Accra',
    region: 'Greater Accra',
    gpsAddress: 'GA-492-3841',
    totalUnits: 16,
    description: 'Prime 2 & 3 bedroom contemporary apartments with borehole water, standby generator, and private security gatehouse.',
    imageUrl: '/images/general_apartment.jpg',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'prop_cantonments',
    landlordId: 'lnd_christian_ahugbah',
    name: 'Cantonments Diplomatic Villas',
    type: 'Residential Townhouse',
    address: '8 Rangoon Link, Cantonments',
    city: 'Accra',
    region: 'Greater Accra',
    gpsAddress: 'GA-112-9023',
    totalUnits: 12,
    description: 'Gated enclave of 3-bedroom executive townhouses close to embassies, international schools, and Jubilee House.',
    imageUrl: '/images/cantonments_townhouses.jpg',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'prop_airport_res',
    landlordId: 'lnd_christian_ahugbah',
    name: 'Airport Residential Heights',
    type: 'Apartment Complex',
    address: '22 Senchi Street, Airport Residential Area',
    city: 'Accra',
    region: 'Greater Accra',
    gpsAddress: 'GA-084-5120',
    totalUnits: 10,
    description: 'Boutique residential complex offering serviced suites with underground parking and perimeter electric fencing.',
    imageUrl: '/images/general_apartment.jpg',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prop_osu_commercial',
    landlordId: 'lnd_christian_ahugbah',
    name: 'Osu Oxford Plaza',
    type: 'Commercial Office',
    address: '45 Oxford Street, Osu',
    city: 'Accra',
    region: 'Greater Accra',
    gpsAddress: 'GA-031-7788',
    totalUnits: 9,
    description: 'High-footfall commercial suites and professional creative offices along vibrant Oxford Street.',
    imageUrl: '/images/general_apartment.jpg',
    createdAt: '2026-02-10T11:00:00Z',
  },
];

export const INITIAL_UNITS: Unit[] = [
  // East Legon units
  {
    id: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    unitNumber: 'A1',
    type: '2 Bedroom Luxury',
    monthlyRent: 1500,
    securityDeposit: 3000,
    status: 'Occupied',
    currentTenantId: 'ten_kofi_mensah',
    amenities: ['Prepaid ECG Meter', 'Ghana Water', 'Split AC Units', 'Balcony', 'Dedicated Parking'],
  },
  {
    id: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    unitNumber: 'A2',
    type: '2 Bedroom Standard',
    monthlyRent: 1400,
    securityDeposit: 2800,
    status: 'Occupied',
    currentTenantId: 'ten_ama_serwaa',
    amenities: ['Prepaid ECG Meter', 'Ghana Water', 'Split AC Units', 'Parking Space'],
  },
  {
    id: 'unit_el_b1',
    propertyId: 'prop_east_legon',
    unitNumber: 'B1',
    type: '3 Bedroom Penthouse',
    monthlyRent: 2600,
    securityDeposit: 5200,
    status: 'Occupied',
    currentTenantId: 'ten_kwame_addo',
    amenities: ['Prepaid ECG Meter', 'Borehole Backup', 'Standby Gen', 'Terrace', 'Fitted Kitchen'],
  },
  {
    id: 'unit_el_b2',
    propertyId: 'prop_east_legon',
    unitNumber: 'B2',
    type: '2 Bedroom Standard',
    monthlyRent: 1500,
    securityDeposit: 3000,
    status: 'Vacant',
    amenities: ['Prepaid ECG Meter', 'Ghana Water', 'Parking Space'],
  },
  // Cantonments units
  {
    id: 'unit_cant_t1',
    propertyId: 'prop_cantonments',
    unitNumber: 'Villa 1',
    type: '3 Bedroom Townhouse',
    monthlyRent: 3800,
    securityDeposit: 7600,
    status: 'Occupied',
    currentTenantId: 'ten_akosua_osei',
    amenities: ['Private Garden', 'Inverter Solar Backup', 'En-suite Bedrooms', 'Maid Quarters', '2-Car Garage'],
  },
  {
    id: 'unit_cant_t2',
    propertyId: 'prop_cantonments',
    unitNumber: 'Villa 2',
    type: '3 Bedroom Townhouse',
    monthlyRent: 3800,
    securityDeposit: 7600,
    status: 'Occupied',
    currentTenantId: 'ten_emmanuel_b',
    amenities: ['Private Garden', 'Inverter Solar Backup', 'En-suite Bedrooms', 'Maid Quarters', '2-Car Garage'],
  },
  {
    id: 'unit_cant_t3',
    propertyId: 'prop_cantonments',
    unitNumber: 'Villa 3',
    type: '3 Bedroom Townhouse',
    monthlyRent: 3800,
    securityDeposit: 7600,
    status: 'Vacant',
    amenities: ['Private Garden', 'Ghana Water', 'En-suite Bedrooms', 'Garage'],
  },
  // Airport Residential units
  {
    id: 'unit_air_101',
    propertyId: 'prop_airport_res',
    unitNumber: 'Ste 101',
    type: '1 Bedroom Executive',
    monthlyRent: 2100,
    securityDeposit: 4200,
    status: 'Occupied',
    currentTenantId: 'ten_abena_frimpong',
    amenities: ['Full Furnished', 'High-Speed Fiber', 'Gym Access', 'Underground Parking'],
  },
  {
    id: 'unit_air_102',
    propertyId: 'prop_airport_res',
    unitNumber: 'Ste 102',
    type: '2 Bedroom Executive',
    monthlyRent: 3200,
    securityDeposit: 6400,
    status: 'Vacant',
    amenities: ['Furnished', 'Fiber Internet', 'Swimming Pool', 'Security Guard'],
  },
  // Osu Commercial units
  {
    id: 'unit_osu_shop1',
    propertyId: 'prop_osu_commercial',
    unitNumber: 'Shop G-01',
    type: 'Commercial Retail / Shop',
    monthlyRent: 2900,
    securityDeposit: 5800,
    status: 'Occupied',
    currentTenantId: 'ten_yaw_darko',
    amenities: ['Street Glass Frontage', 'Commercial 3-Phase ECG', 'Security Roller Shutters'],
  },
  {
    id: 'unit_osu_off2',
    propertyId: 'prop_osu_commercial',
    unitNumber: 'Office 201',
    type: 'Executive Office Suite',
    monthlyRent: 2400,
    securityDeposit: 4800,
    status: 'Vacant',
    amenities: ['Open Work Space', 'Meeting Room Partition', 'Kitchenette', 'Restrooms'],
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'ten_kofi_mensah',
    fullName: 'Kofi Mensah',
    phone: '024 412 8934',
    email: 'kofi.mensah@techhub.gh',
    idType: 'Ghana Card',
    idNumber: 'GHA-723456789-0',
    occupation: 'Senior Software Engineer, Hubtel Ghana',
    emergencyContactName: 'Grace Mensah (Sister)',
    emergencyContactPhone: '020 918 2736',
    portalToken: 'rf_tok_kofi_mensah',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'ten_ama_serwaa',
    fullName: 'Ama Serwaa',
    phone: '050 382 9102',
    email: 'ama.serwaa@consulting.com',
    idType: 'Ghana Card',
    idNumber: 'GHA-619283740-4',
    occupation: 'Financial Analyst, Deloitte Ghana',
    emergencyContactName: 'Kwadwo Serwaa (Father)',
    emergencyContactPhone: '024 333 8811',
    portalToken: 'rf_tok_ama_serwaa',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'ten_kwame_addo',
    fullName: 'Kwame Addo',
    phone: '024 819 2831',
    email: 'kwame.addo@energygh.com',
    idType: 'Ghana Card',
    idNumber: 'GHA-918273645-1',
    occupation: 'Petroleum Engineer, Tullow Oil',
    emergencyContactName: 'Yaa Addo (Wife)',
    emergencyContactPhone: '055 491 8273',
    portalToken: 'rf_tok_kwame_addo',
    createdAt: '2026-07-01T11:00:00Z',
  },
  {
    id: 'ten_akosua_osei',
    fullName: 'Akosua Osei',
    phone: '027 519 2048',
    email: 'akosua.osei@lawchambers.gh',
    idType: 'Ghana Card',
    idNumber: 'GHA-501928374-9',
    occupation: 'Managing Partner, Lex Veritas Ghana',
    emergencyContactName: 'Dr. Joseph Osei (Brother)',
    emergencyContactPhone: '024 112 9944',
    portalToken: 'rf_tok_akosua_osei',
    createdAt: '2026-06-15T08:30:00Z',
  },
  {
    id: 'ten_emmanuel_b',
    fullName: 'Emmanuel Boateng',
    phone: '024 991 8274',
    email: 'e.boateng@goldfields.com',
    idType: 'Ghana Card',
    idNumber: 'GHA-339182746-5',
    occupation: 'Mining Operations Specialist',
    emergencyContactName: 'Linda Boateng',
    emergencyContactPhone: '020 448 1920',
    portalToken: 'rf_tok_emmanuel_b',
    createdAt: '2026-05-10T12:00:00Z',
  },
  {
    id: 'ten_abena_frimpong',
    fullName: 'Abena Frimpong',
    phone: '055 771 9283',
    email: 'abena.frimpong@who.int',
    idType: 'Ghana Card',
    idNumber: 'GHA-849201938-7',
    occupation: 'Regional Health Officer, WHO AFRO',
    emergencyContactName: 'Samuel Frimpong',
    emergencyContactPhone: '024 882 1199',
    portalToken: 'rf_tok_abena_frimpong',
    createdAt: '2026-07-20T14:00:00Z',
  },
  {
    id: 'ten_yaw_darko',
    fullName: 'Yaw Darko',
    phone: '024 332 9911',
    email: 'darko.creatives@gmail.com',
    idType: 'Ghana Card',
    idNumber: 'GHA-449182736-2',
    occupation: 'Creative Director & Retail Owner',
    emergencyContactName: 'Naa Darko',
    emergencyContactPhone: '020 994 8832',
    portalToken: 'rf_tok_yaw_darko',
    createdAt: '2026-04-12T09:15:00Z',
  },
];

export const INITIAL_TENANCIES: Tenancy[] = [
  {
    id: 'tcy_kofi_mensah',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    startDate: '2026-09-01',
    endDate: '2027-08-31',
    rentAmount: 1500, // GH¢1,500/month as in doc
    billingFrequency: 'MONTHLY',
    advanceMonths: 12,
    securityDeposit: 3000,
    dueDay: 1,
    status: 'Active',
    agreementNotes: 'Standard 1-year tenancy agreement with 12 months upfront payment in Ghanaian convention. Monthly breakdown tracked.',
    createdAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'tcy_ama_serwaa',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    startDate: '2026-08-01',
    endDate: '2027-07-31',
    rentAmount: 1400,
    billingFrequency: 'MONTHLY',
    advanceMonths: 6,
    securityDeposit: 2800,
    dueDay: 1,
    status: 'Active',
    agreementNotes: '6 months advance rent renewable on expiry.',
    createdAt: '2026-07-25T11:00:00Z',
  },
  {
    id: 'tcy_kwame_addo',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_kwame_addo',
    unitId: 'unit_el_b1',
    propertyId: 'prop_east_legon',
    startDate: '2026-07-01',
    endDate: '2027-06-30',
    rentAmount: 2600,
    billingFrequency: 'MONTHLY',
    advanceMonths: 12,
    securityDeposit: 5200,
    dueDay: 1,
    status: 'Active',
    createdAt: '2026-06-20T12:00:00Z',
  },
  {
    id: 'tcy_akosua_osei',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_akosua_osei',
    unitId: 'unit_cant_t1',
    propertyId: 'prop_cantonments',
    startDate: '2026-06-01',
    endDate: '2027-05-31',
    rentAmount: 3800,
    billingFrequency: 'MONTHLY',
    advanceMonths: 12,
    securityDeposit: 7600,
    dueDay: 1,
    status: 'Active',
    createdAt: '2026-05-25T14:00:00Z',
  },
  {
    id: 'tcy_emmanuel_b',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_emmanuel_b',
    unitId: 'unit_cant_t2',
    propertyId: 'prop_cantonments',
    startDate: '2026-05-01',
    endDate: '2027-04-30',
    rentAmount: 3800,
    billingFrequency: 'MONTHLY',
    advanceMonths: 12,
    securityDeposit: 7600,
    dueDay: 1,
    status: 'Active',
    createdAt: '2026-04-20T09:00:00Z',
  },
  {
    id: 'tcy_abena_frimpong',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_abena_frimpong',
    unitId: 'unit_air_101',
    propertyId: 'prop_airport_res',
    startDate: '2026-07-01',
    endDate: '2027-06-30',
    rentAmount: 2100,
    billingFrequency: 'MONTHLY',
    advanceMonths: 6,
    securityDeposit: 4200,
    dueDay: 1,
    status: 'Active',
    createdAt: '2026-06-28T15:00:00Z',
  },
  {
    id: 'tcy_yaw_darko',
    landlordId: 'lnd_christian_ahugbah',
    tenantId: 'ten_yaw_darko',
    unitId: 'unit_osu_shop1',
    propertyId: 'prop_osu_commercial',
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    rentAmount: 2900,
    billingFrequency: 'MONTHLY',
    advanceMonths: 12,
    securityDeposit: 5800,
    dueDay: 1,
    status: 'Active',
    createdAt: '2026-03-25T16:00:00Z',
  },
];

// Matches the exact Ledger and Invoices from PDF Page 3, 4, 5
export const INITIAL_INVOICES: RentInvoice[] = [
  // Kofi Mensah September Rent: GH¢1,500 billed, Paid GH¢1,500 via two payments (GH¢1,000 + GH¢500)
  {
    id: 'inv_kofi_sep_2026',
    invoiceNumber: 'INV-2026-001',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    dueDate: '2026-09-01',
    amount: 1500,
    paidAmount: 1500,
    balance: 0,
    status: 'Paid',
    createdAt: '2026-08-25T00:00:00Z',
  },
  // Kofi Mensah October Rent: GH¢1,500 billed, currently Due / Overdue with GH¢1,500 outstanding
  {
    id: 'inv_kofi_oct_2026',
    invoiceNumber: 'INV-2026-008',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 1500,
    paidAmount: 0,
    balance: 1500,
    status: 'Due',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Ama Serwaa September: Paid
  {
    id: 'inv_ama_sep_2026',
    invoiceNumber: 'INV-2026-002',
    tenancyId: 'tcy_ama_serwaa',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    dueDate: '2026-09-01',
    amount: 1400,
    paidAmount: 1400,
    balance: 0,
    status: 'Paid',
    createdAt: '2026-08-25T00:00:00Z',
  },
  // Ama Serwaa October: Partially Paid (GH¢1,400 invoice receiving GH¢900, GH¢500 balance outstanding)
  {
    id: 'inv_ama_oct_2026',
    invoiceNumber: 'INV-2026-009',
    tenancyId: 'tcy_ama_serwaa',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 1400,
    paidAmount: 900,
    balance: 500,
    status: 'Partially Paid',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Kwame Addo October: Paid GH¢2,600
  {
    id: 'inv_kwame_oct_2026',
    invoiceNumber: 'INV-2026-010',
    tenancyId: 'tcy_kwame_addo',
    tenantId: 'ten_kwame_addo',
    unitId: 'unit_el_b1',
    propertyId: 'prop_east_legon',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 2600,
    paidAmount: 2600,
    balance: 0,
    status: 'Paid',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Akosua Osei October: Overdue GH¢3,800
  {
    id: 'inv_akosua_oct_2026',
    invoiceNumber: 'INV-2026-011',
    tenancyId: 'tcy_akosua_osei',
    tenantId: 'ten_akosua_osei',
    unitId: 'unit_cant_t1',
    propertyId: 'prop_cantonments',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-09-25',
    amount: 3800,
    paidAmount: 0,
    balance: 3800,
    status: 'Overdue',
    createdAt: '2026-09-15T00:00:00Z',
  },
  // Emmanuel Boateng October: Paid GH¢3,800
  {
    id: 'inv_emmanuel_oct_2026',
    invoiceNumber: 'INV-2026-012',
    tenancyId: 'tcy_emmanuel_b',
    tenantId: 'ten_emmanuel_b',
    unitId: 'unit_cant_t2',
    propertyId: 'prop_cantonments',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 3800,
    paidAmount: 3800,
    balance: 0,
    status: 'Paid',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Abena Frimpong October: Paid GH¢2,100
  {
    id: 'inv_abena_oct_2026',
    invoiceNumber: 'INV-2026-013',
    tenancyId: 'tcy_abena_frimpong',
    tenantId: 'ten_abena_frimpong',
    unitId: 'unit_air_101',
    propertyId: 'prop_airport_res',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 2100,
    paidAmount: 2100,
    balance: 0,
    status: 'Paid',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Yaw Darko September: Overdue GH¢2,900
  {
    id: 'inv_yaw_sep_2026',
    invoiceNumber: 'INV-2026-005',
    tenancyId: 'tcy_yaw_darko',
    tenantId: 'ten_yaw_darko',
    unitId: 'unit_osu_shop1',
    propertyId: 'prop_osu_commercial',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    dueDate: '2026-09-01',
    amount: 2900,
    paidAmount: 1400,
    balance: 1500,
    status: 'Overdue',
    createdAt: '2026-08-25T00:00:00Z',
  },
  // Yaw Darko October: Due GH¢2,900
  {
    id: 'inv_yaw_oct_2026',
    invoiceNumber: 'INV-2026-014',
    tenancyId: 'tcy_yaw_darko',
    tenantId: 'ten_yaw_darko',
    unitId: 'unit_osu_shop1',
    propertyId: 'prop_osu_commercial',
    periodStart: '2026-10-01',
    periodEnd: '2026-10-31',
    dueDate: '2026-10-01',
    amount: 2900,
    paidAmount: 0,
    balance: 2900,
    status: 'Due',
    createdAt: '2026-09-25T00:00:00Z',
  },
  // Upcoming November Invoices
  {
    id: 'inv_kofi_nov_2026',
    invoiceNumber: 'INV-2026-020',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    periodStart: '2026-11-01',
    periodEnd: '2026-11-30',
    dueDate: '2026-11-01',
    amount: 1500,
    paidAmount: 0,
    balance: 1500,
    status: 'Upcoming',
    createdAt: '2026-10-01T00:00:00Z',
  },
];

// Payments matching the PDF Section 7 & 8 ledger (03 Sep MoMo GH¢1,000, 15 Sep Cash/Bank GH¢500)
export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay_kofi_001',
    paymentReference: 'RF-PAY-2026-0031',
    providerReference: 'MTN-MOMO-8392147',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    amount: 1000,
    paymentMethod: 'Mobile Money',
    providerNetwork: 'MTN MoMo',
    paymentDate: '2026-09-03T11:42:00Z',
    status: 'Confirmed',
    payerName: 'Kofi Mensah',
    payerPhone: '0244128934',
    receiptNumber: 'RF-REC-2026-0031',
    notes: 'Partial payment towards September Rent via MTN MoMo.',
    allocations: [
      {
        id: 'alloc_001',
        paymentId: 'pay_kofi_001',
        invoiceId: 'inv_kofi_sep_2026',
        amountAllocated: 1000,
        allocatedAt: '2026-09-03T11:42:05Z',
      },
    ],
  },
  {
    id: 'pay_kofi_002',
    paymentReference: 'RF-PAY-2026-0038',
    providerReference: 'ECB-TRF-9102834',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    amount: 500,
    paymentMethod: 'Bank Transfer',
    providerNetwork: 'Ecobank Ghana',
    paymentDate: '2026-09-15T15:20:00Z',
    status: 'Confirmed',
    payerName: 'Kofi Mensah',
    payerPhone: '0244128934',
    receiptNumber: 'RF-REC-2026-0038',
    notes: 'Settlement of remaining balance for September Rent.',
    allocations: [
      {
        id: 'alloc_002',
        paymentId: 'pay_kofi_002',
        invoiceId: 'inv_kofi_sep_2026',
        amountAllocated: 500,
        allocatedAt: '2026-09-15T15:20:05Z',
      },
    ],
  },
  {
    id: 'pay_ama_001',
    paymentReference: 'RF-PAY-2026-0040',
    providerReference: 'VOD-CASH-771829',
    tenancyId: 'tcy_ama_serwaa',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    amount: 1400,
    paymentMethod: 'Mobile Money',
    providerNetwork: 'Telecel Cash',
    paymentDate: '2026-09-02T09:10:00Z',
    status: 'Confirmed',
    payerName: 'Ama Serwaa',
    payerPhone: '0503829102',
    receiptNumber: 'RF-REC-2026-0040',
    notes: 'Full September rent payment via Telecel Cash.',
    allocations: [
      {
        id: 'alloc_003',
        paymentId: 'pay_ama_001',
        invoiceId: 'inv_ama_sep_2026',
        amountAllocated: 1400,
        allocatedAt: '2026-09-02T09:10:05Z',
      },
    ],
  },
  {
    id: 'pay_ama_002',
    paymentReference: 'RF-PAY-2026-0045',
    providerReference: 'MTN-MOMO-9102847',
    tenancyId: 'tcy_ama_serwaa',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    amount: 900,
    paymentMethod: 'Mobile Money',
    providerNetwork: 'MTN MoMo',
    paymentDate: '2026-10-01T08:30:00Z',
    status: 'Confirmed',
    payerName: 'Ama Serwaa',
    payerPhone: '0503829102',
    receiptNumber: 'RF-REC-2026-0045',
    notes: 'Part-payment towards October Rent (GH¢500 balance remaining).',
    allocations: [
      {
        id: 'alloc_004',
        paymentId: 'pay_ama_002',
        invoiceId: 'inv_ama_oct_2026',
        amountAllocated: 900,
        allocatedAt: '2026-10-01T08:30:05Z',
      },
    ],
  },
  {
    id: 'pay_kwame_001',
    paymentReference: 'RF-PAY-2026-0046',
    providerReference: 'GCB-TRF-4910283',
    tenancyId: 'tcy_kwame_addo',
    tenantId: 'ten_kwame_addo',
    unitId: 'unit_el_b1',
    propertyId: 'prop_east_legon',
    amount: 2600,
    paymentMethod: 'Bank Transfer',
    providerNetwork: 'GCB Bank',
    paymentDate: '2026-09-30T16:45:00Z',
    status: 'Confirmed',
    payerName: 'Kwame Addo',
    payerPhone: '0248192831',
    receiptNumber: 'RF-REC-2026-0046',
    notes: 'October Rent settled in full.',
    allocations: [
      {
        id: 'alloc_005',
        paymentId: 'pay_kwame_001',
        invoiceId: 'inv_kwame_oct_2026',
        amountAllocated: 2600,
        allocatedAt: '2026-09-30T16:45:05Z',
      },
    ],
  },
  {
    id: 'pay_emmanuel_001',
    paymentReference: 'RF-PAY-2026-0047',
    providerReference: 'MTN-MOMO-4481920',
    tenancyId: 'tcy_emmanuel_b',
    tenantId: 'ten_emmanuel_b',
    unitId: 'unit_cant_t2',
    propertyId: 'prop_cantonments',
    amount: 3800,
    paymentMethod: 'Mobile Money',
    providerNetwork: 'MTN MoMo',
    paymentDate: '2026-09-28T14:15:00Z',
    status: 'Confirmed',
    payerName: 'Emmanuel Boateng',
    payerPhone: '0249918274',
    receiptNumber: 'RF-REC-2026-0047',
    notes: 'Prompt payment for October tenancy.',
    allocations: [
      {
        id: 'alloc_006',
        paymentId: 'pay_emmanuel_001',
        invoiceId: 'inv_emmanuel_oct_2026',
        amountAllocated: 3800,
        allocatedAt: '2026-09-28T14:15:05Z',
      },
    ],
  },
  {
    id: 'pay_abena_001',
    paymentReference: 'RF-PAY-2026-0048',
    providerReference: 'CARD-VISA-901823',
    tenancyId: 'tcy_abena_frimpong',
    tenantId: 'ten_abena_frimpong',
    unitId: 'unit_air_101',
    propertyId: 'prop_airport_res',
    amount: 2100,
    paymentMethod: 'Card',
    providerNetwork: 'Visa Ghana / Ecobank',
    paymentDate: '2026-09-29T10:00:00Z',
    status: 'Confirmed',
    payerName: 'Abena Frimpong',
    payerPhone: '0557719283',
    receiptNumber: 'RF-REC-2026-0048',
    notes: 'Card payment via RentFlow online portal.',
    allocations: [
      {
        id: 'alloc_007',
        paymentId: 'pay_abena_001',
        invoiceId: 'inv_abena_oct_2026',
        amountAllocated: 2100,
        allocatedAt: '2026-09-29T10:00:05Z',
      },
    ],
  },
];

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    id: 'rec_0031',
    receiptNumber: 'RF-REC-2026-0031',
    paymentId: 'pay_kofi_001',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    amountPaid: 1000,
    periodCovered: '01 Sep 2026 - 30 Sep 2026 (Part Payment)',
    issueDate: '2026-09-03',
    issuedBy: 'RentFlow Automated Billing System',
    balanceRemaining: 500,
    notes: 'MoMo transaction ref: MTN-MOMO-8392147. Thank you for your payment.',
  },
  {
    id: 'rec_0038',
    receiptNumber: 'RF-REC-2026-0038',
    paymentId: 'pay_kofi_002',
    tenancyId: 'tcy_kofi_mensah',
    tenantId: 'ten_kofi_mensah',
    unitId: 'unit_el_a1',
    propertyId: 'prop_east_legon',
    amountPaid: 500,
    periodCovered: '01 Sep 2026 - 30 Sep 2026 (Balance Settlement)',
    issueDate: '2026-09-15',
    issuedBy: 'RentFlow Automated Billing System',
    balanceRemaining: 0,
    notes: 'Bank Transfer ref: ECB-TRF-9102834. September rent fully satisfied.',
  },
  {
    id: 'rec_0045',
    receiptNumber: 'RF-REC-2026-0045',
    paymentId: 'pay_ama_002',
    tenancyId: 'tcy_ama_serwaa',
    tenantId: 'ten_ama_serwaa',
    unitId: 'unit_el_a2',
    propertyId: 'prop_east_legon',
    amountPaid: 900,
    periodCovered: '01 Oct 2026 - 31 Oct 2026 (Part Payment)',
    issueDate: '2026-10-01',
    issuedBy: 'RentFlow Automated Billing System',
    balanceRemaining: 500,
    notes: 'MoMo transaction ref: MTN-MOMO-9102847. GH¢500 remaining for October.',
  },
  {
    id: 'rec_0046',
    receiptNumber: 'RF-REC-2026-0046',
    paymentId: 'pay_kwame_001',
    tenancyId: 'tcy_kwame_addo',
    tenantId: 'ten_kwame_addo',
    unitId: 'unit_el_b1',
    propertyId: 'prop_east_legon',
    amountPaid: 2600,
    periodCovered: '01 Oct 2026 - 31 Oct 2026',
    issueDate: '2026-09-30',
    issuedBy: 'RentFlow Automated Billing System',
    balanceRemaining: 0,
    notes: 'GCB Bank transfer ref: GCB-TRF-4910283.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationRecord[] = [
  {
    id: 'notif_001',
    tenantId: 'ten_kofi_mensah',
    tenancyId: 'tcy_kofi_mensah',
    invoiceId: 'inv_kofi_oct_2026',
    channel: 'SMS',
    recipient: '0244128934',
    title: 'October Rent Due Reminder',
    message: 'Hello Kofi, your rent obligation of GH¢1,500 for Unit A1, East Legon is due today 01 Oct 2026. Pay securely via MTN MoMo on your portal: rentflow.gh/portal?token=rf_tok_kofi_mensah',
    status: 'Sent',
    createdAt: '2026-10-01T07:00:00Z',
    sentAt: '2026-10-01T07:00:05Z',
    providerReference: 'HUBTEL-SMS-910283',
  },
  {
    id: 'notif_002',
    tenantId: 'ten_kofi_mensah',
    invoiceId: 'inv_kofi_sep_2026',
    channel: 'WhatsApp',
    recipient: '+233244128934',
    title: 'Payment Received & Receipt Ready',
    message: 'Thank you Kofi! We received your payment of GH¢500 via Ecobank. Your receipt #RF-REC-2026-0038 is generated. September rent balance is now GH¢0. Download receipt: rentflow.gh/receipt/RF-REC-2026-0038',
    status: 'Sent',
    createdAt: '2026-09-15T15:20:10Z',
    sentAt: '2026-09-15T15:20:12Z',
    providerReference: 'WABA-MSG-448102',
  },
  {
    id: 'notif_003',
    tenantId: 'ten_akosua_osei',
    tenancyId: 'tcy_akosua_osei',
    invoiceId: 'inv_akosua_oct_2026',
    channel: 'WhatsApp',
    recipient: '+233275192048',
    title: 'Urgent: Overdue Rent Notice',
    message: 'Dear Lawyer Akosua Osei, your rent for Cantonments Villa 1 of GH¢3,800 is overdue since 25 Sep 2026. Please click the link to settle via MoMo/Bank transfer: rentflow.gh/portal?token=rf_tok_akosua_osei',
    status: 'Queued',
    createdAt: '2026-10-01T08:00:00Z',
  },
  {
    id: 'notif_004',
    tenantId: 'ten_yaw_darko',
    tenancyId: 'tcy_yaw_darko',
    invoiceId: 'inv_yaw_sep_2026',
    channel: 'SMS',
    recipient: '0243329911',
    title: 'Arrears Balance Notice',
    message: 'Notice: Shop G-01 Osu Oxford Plaza has an outstanding balance of GH¢1,500 from September. Kindly arrange payment to avoid statutory notice.',
    status: 'Queued',
    createdAt: '2026-10-01T08:15:00Z',
  },
  {
    id: 'notif_005',
    tenantId: 'ten_ama_serwaa',
    channel: 'In-App',
    recipient: 'ama.serwaa@consulting.com',
    title: 'Part Payment Acknowledged',
    message: 'GH¢900 received via MTN MoMo. Remaining balance for October rent is GH¢500.',
    status: 'Sent',
    createdAt: '2026-10-01T08:31:00Z',
    sentAt: '2026-10-01T08:31:01Z',
  },
];

export const INITIAL_MAINTENANCE: MaintenanceTicket[] = [
  {
    id: 'maint_001',
    propertyId: 'prop_east_legon',
    unitId: 'unit_el_a1',
    tenantId: 'ten_kofi_mensah',
    title: 'Master Bathroom Water Heater Pressure Valve',
    description: 'The pressure release valve is dripping slightly when the water heater is active.',
    category: 'Plumbing',
    priority: 'Medium',
    status: 'In Progress',
    reportedDate: '2026-09-28',
    estimatedCost: 350,
  },
  {
    id: 'maint_002',
    propertyId: 'prop_cantonments',
    title: 'Borehole Submersible Pump Servicing',
    description: 'Quarterly routine servicing for the high-yield borehole filtration unit.',
    category: 'Water Supply',
    priority: 'Low',
    status: 'Resolved',
    reportedDate: '2026-09-20',
    estimatedCost: 850,
  },
  {
    id: 'maint_003',
    propertyId: 'prop_osu_commercial',
    unitId: 'unit_osu_shop1',
    tenantId: 'ten_yaw_darko',
    title: 'Air Conditioning Refrigerant Top-up',
    description: 'Main retail area split unit is not cooling sufficiently during peak afternoon sun.',
    category: 'AC / HVAC',
    priority: 'High',
    status: 'Open',
    reportedDate: '2026-09-30',
    estimatedCost: 480,
  },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp_001',
    propertyId: 'prop_east_legon',
    category: 'ECG Electricity',
    description: 'Common areas, security lights & electric fence monthly prepaid credit',
    amount: 1200,
    date: '2026-09-05',
    vendorName: 'Electricity Company of Ghana (ECG)',
    receiptReference: 'ECG-PAY-918204',
  },
  {
    id: 'exp_002',
    propertyId: 'prop_east_legon',
    category: 'Facility Security',
    description: '24/7 Security guard patrol services for September',
    amount: 2200,
    date: '2026-09-01',
    vendorName: 'Omega Security Services Ghana',
    receiptReference: 'OMG-INV-4412',
  },
  {
    id: 'exp_003',
    propertyId: 'prop_cantonments',
    category: 'Grounds Maintenance',
    description: 'Landscaping, palm pruning and compound pressure wash',
    amount: 750,
    date: '2026-09-12',
    vendorName: 'Verdant Green Landscaping',
    receiptReference: 'VGL-REC-1092',
  },
  {
    id: 'exp_004',
    propertyId: 'prop_airport_res',
    category: 'Ghana Water Bill',
    description: 'Ghana Water Company commercial supply & reservoir top-up',
    amount: 980,
    date: '2026-09-18',
    vendorName: 'Ghana Water Company Ltd',
    receiptReference: 'GWCL-ACC-8831',
  },
];
